// import type { Metadata } from "next";
// import "./globals.css";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html>
//       <body>
//         {children}
//       </body>
//     </html>
//   );
// }






import { Geist } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";

const geist = Geist({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" className={geist.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
